name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud
        run: gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: Build and push Docker image
        run: |
          gcloud builds submit \
            --tag europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/invnudge-docker/auth-service .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy invnudge-auth \
            --image europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/invnudge-docker/auth-service \
            --region europe-central2 \
            --platform managed \
            --allow-unauthenticated \
            --cpu=2 \
            --memory=8Gi
