name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/invnudge-docker/auth-service:latest .

      - name: Push Docker image
        run: docker push europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/invnudge-docker/auth-service:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy invnudge-auth \
            --image=europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/invnudge-docker/auth-service:latest \
            --platform=managed \
            --region=europe-central2 \
            --allow-unauthenticated \
            --cpu=2 \
            --memory=8Gi \
            --port=8080
